/*
  Workout content lives here.
  LIB  = every exercise: name, YouTube search terms (q), form steps, and tips.
  DAYS = the weekly plan. Each plan item points at a LIB key and gives
         sets, reps (text) or time (seconds), rest (seconds between sets),
         and after (seconds before the next exercise, default 30).
  Edit freely; the app rebuilds itself from this data.
*/
/* ---------- Exercise library ---------- */
var LIB = {
  warm_legs:{name:"Warm-up",q:"leg swings hip circles warm up",
    steps:["Easy crosstrainer for about 4 minutes, just enough to get warm.","10 leg swings per leg, front to back, holding something for balance.","10 hip circles in each direction."],
    tips:["This should feel easy. Save your effort for the main work."]},
  warm_upper:{name:"Warm-up",q:"arm circles shoulder warm up",
    steps:["Easy crosstrainer for about 4 minutes.","10 arm circles forwards, then 10 backwards.","10 slow shoulder rolls in each direction."],
    tips:["Start the arm circles small and let them get bigger."]},
  warm_row:{name:"Warm-up row",q:"rowing machine technique beginner",
    steps:["Row at a very easy pace.","On each stroke: push with the legs, lean back slightly, then pull the handle to your lower ribs.","Return in reverse: arms out, body forward, then bend the knees."],
    tips:["Most of the power comes from the legs, not the arms.","Don't hunch over at the front of the stroke."]},
  warm_rotation:{name:"Warm-up",q:"standing torso twist warm up",
    steps:["Easy row for about 4 minutes.","10 standing torso twists each side, arms loose.","10 arm circles in each direction."],
    tips:["Let the hips turn a little with the twists rather than forcing the spine."]},
  warm_cross:{name:"Warm-up",q:"elliptical cross trainer technique",
    steps:["Crosstrainer at an easy, steady pace.","Stand tall and use the handles, pushing and pulling."],
    tips:["Don't lean on the handles and let the machine carry you."]},

  squat:{name:"Bodyweight squats",q:"bodyweight squat form",
    steps:["Feet shoulder-width apart, toes turned out slightly.","Push your hips back and bend your knees, like sitting into a low chair.","Go as low as you can while keeping heels down and chest up.","Drive through your whole foot to stand back up."],
    tips:["Knees should follow the line of your toes, not cave inwards.","Don't let your lower back round at the bottom."]},
  bridge:{name:"Glute bridges",q:"glute bridge form",
    steps:["Lie on your back, knees bent, feet flat and hip-width apart.","Squeeze your glutes and push your hips up until knees, hips and shoulders line up.","Hold for one second at the top.","Lower slowly."],
    tips:["Push through your heels.","Don't arch your lower back to get extra height."]},
  lunge:{name:"Reverse lunges",q:"reverse lunge form",
    steps:["Stand tall, feet hip-width apart.","Step one foot back and lower until both knees are bent to about 90 degrees.","Your back knee should hover just above the floor.","Push through the front heel to return to standing."],
    tips:["Keep your torso upright.","Hold a light dumbbell in each hand once bodyweight feels easy."]},
  calf:{name:"Calf raises",q:"calf raise form",
    steps:["Stand with feet hip-width apart, holding something for balance.","Rise up onto the balls of your feet as high as you can.","Pause at the top.","Lower slowly, over about 2 seconds."],
    tips:["No bouncing at the bottom.","Doing them on a step edge gives a bigger stretch."]},
  plank:{name:"Plank",q:"forearm plank form",
    steps:["Forearms on the floor, elbows directly under your shoulders.","Step your feet back so your body is straight from head to heels.","Brace your stomach as if someone was about to poke it, and squeeze your glutes.","Breathe steadily and hold."],
    tips:["Hips shouldn't sag down or pike up.","Drop to your knees if your form breaks."]},
  side_plank:{name:"Side plank",q:"side plank form",
    steps:["Lie on your side with your elbow under your shoulder.","Stack your feet, or stagger them for balance.","Lift your hips until your body is in a straight line.","Hold without letting your hips drop."],
    tips:["Bending the knees and resting on them is a fine starting version."]},
  dead_bug:{name:"Dead bug",q:"dead bug exercise form",
    steps:["Lie on your back, arms straight up, knees bent at 90 degrees above your hips.","Press your lower back flat into the floor.","Slowly lower one arm and the opposite leg towards the floor.","Bring them back and switch sides."],
    tips:["If your lower back lifts off the floor, don't lower as far."]},

  row_steady:{name:"Steady row",q:"rowing machine steady state technique",
    steps:["Legs push first, then lean back slightly, then pull the handle to your lower ribs.","Return in reverse: arms, then body, then legs.","Keep a smooth, steady rhythm."],
    tips:["You should be able to hold a conversation. This is base-building, not a race.","Most of the work comes from the legs."]},
  farmer:{name:"Farmer's carry",q:"farmers carry dumbbell form",
    steps:["Hold a dumbbell in each hand at your sides.","Stand tall with shoulders back and down.","Walk with slow, steady steps, or march on the spot if space is tight.","Grip hard the whole time."],
    tips:["Don't let your shoulders creep up towards your ears.","Don't lean to one side."]},
  wrist_curl:{name:"Wrist curls",q:"dumbbell wrist curl reverse wrist curl",
    steps:["Sit with forearms resting on your thighs, wrists just past your knees.","Palms up: let the dumbbell roll towards your fingertips, then curl your wrist up.","Do your reps, then flip palms down and lift the back of your hand towards the ceiling."],
    tips:["Only your wrists should move, forearms stay still.","Go light. Forearm tendons are easy to irritate."]},
  dead_hang:{name:"Dead hang",q:"dead hang form",
    steps:["Grip a bar overhand, about shoulder-width.","Lift your feet and hang with your arms straight.","Keep your shoulders slightly engaged rather than fully slumped.","Drop down when your grip gives out."],
    tips:["Only use a bar rated to hold your body weight.","Skip this if you don't have one. The carries already cover grip."]},

  pushup:{name:"Push-ups",q:"push up form beginner",
    steps:["Hands slightly wider than your shoulders.","Body straight from head to heels, or head to knees.","Lower your chest to just above the floor, elbows at about 45 degrees from your body.","Push back up."],
    tips:["Knees on the floor or hands on a counter are both fine versions.","Full range beats fast half reps."]},
  db_row:{name:"Dumbbell rows",q:"single arm dumbbell row form",
    steps:["Put one hand and knee on a bench or sturdy chair, the other foot on the floor.","Hold the dumbbell with your arm hanging straight down.","Pull your elbow back past your ribs and squeeze your shoulder blade.","Lower slowly."],
    tips:["Keep your back flat.","Don't twist your body to heave the weight up."]},
  press:{name:"Shoulder press",q:"dumbbell shoulder press form",
    steps:["Hold dumbbells at shoulder height, palms facing forward.","Brace your stomach.","Press straight up until your arms are nearly straight.","Lower back to your shoulders with control."],
    tips:["Don't arch your lower back. Sitting down can help.","Press straight overhead, not out in front."]},
  rear_delt:{name:"Rear delt flyes",q:"dumbbell rear delt fly form",
    steps:["Hinge forward at the hips with a flat back and soft knees.","Let the dumbbells hang below your chest, elbows slightly bent.","Raise your arms out to the sides, squeezing your shoulder blades together.","Lower slowly."],
    tips:["Go very light. This is a small muscle."]},
  rev_wrist:{name:"Reverse wrist curls",q:"reverse wrist curl dumbbell",
    steps:["Sit with forearms on your thighs, palms facing down.","Lift the back of your hand towards the ceiling.","Lower slowly."],
    tips:["This is the motion that keeps a sword tip from wandering.","Very light weight is plenty."]},

  intervals:{name:"Hard effort",q:"elliptical interval training",
    steps:["Push hard on the crosstrainer: faster pace, higher resistance, or both.","When the timer switches to recovery, drop to an easy pace but keep moving."],
    tips:["Hard means you couldn't hold a sentence.","Ease off if you feel dizzy or your form falls apart."]},

  squat_press:{name:"Squat to press",q:"dumbbell squat to press thruster form",
    steps:["Hold dumbbells at your shoulders.","Squat down.","Stand all the way up.","Press the dumbbells overhead, lower them to your shoulders, and repeat."],
    tips:["Finish standing up before you press."]},
  plank_row:{name:"Plank rows",q:"plank row renegade row form",
    steps:["Get into a high plank on your hands, holding the dumbbells.","Set your feet wider than usual for balance.","Row one dumbbell to your ribs without letting your hips twist.","Lower it and switch sides."],
    tips:["Wider feet make it easier.","Knees on the floor is a fine starting version."]},
  woodchop:{name:"Standing woodchoppers",q:"dumbbell woodchopper exercise",
    steps:["Feet shoulder-width apart, holding one dumbbell with both hands.","Start with it up above one shoulder.","Rotate your hips and torso to bring it diagonally down across your body to the opposite hip.","Return under control."],
    tips:["Let your back foot pivot. The movement comes from the hips, just like a cut.","Don't just swing with your arms."]},
  russian:{name:"Russian twists",q:"russian twist form",
    steps:["Sit with knees bent and lean back slightly with a straight back.","Hold your hands together or a light dumbbell.","Rotate your torso side to side, touching the floor next to each hip."],
    tips:["Keeping your feet on the floor is fine, and kinder on the lower back.","Rotate your ribcage, not just your arms."]},
  bird_dog:{name:"Bird dogs",q:"bird dog exercise form",
    steps:["Start on your hands and knees.","Reach one arm forward and the opposite leg back until both are straight.","Hold for 1 to 2 seconds.","Return and switch sides."],
    tips:["Keep your hips level, as if balancing a cup on your lower back.","Move slowly."]},

  easy_cardio:{name:"Easy row or crosstrainer",q:"low intensity steady state cardio",
    steps:["Pick whichever machine you fancy.","Keep the pace very easy, well below Tuesday's row."],
    tips:["You should be able to chat comfortably. It shouldn't feel like a workout."]},
  mobility:{name:"Mobility flow",q:"full body mobility routine beginner",
    steps:["Shoulder circles.","Cat-cow on hands and knees.","Hip openers, like deep lunges with a slight twist.","Wrist rotations.","Thoracic rotations: on hands and knees, one hand behind your head, rotate the elbow up to the ceiling.","A few slow reps of each, then repeat."],
    tips:["Move gently. Nothing should hurt."]},

  cool_legs:{name:"Cool-down stretches",q:"quad hamstring hip flexor stretch",
    steps:["Quad stretch: 30 seconds per leg.","Hamstring stretch: 30 seconds per leg.","Hip flexor stretch in a half-kneeling lunge: 30 seconds per side."],
    tips:["Ease into stretches, don't bounce."]},
  cool_grip:{name:"Cool-down stretches",q:"forearm stretch wrist flexor extensor",
    steps:["Arm out straight, palm up, gently pull your fingers back: 30 seconds each arm.","Palm down, gently pull your hand towards you: 30 seconds each arm.","Finish with slow shoulder rolls."],
    tips:["Gentle pressure only."]},
  cool_upper:{name:"Cool-down stretches",q:"doorway chest stretch cross body shoulder stretch",
    steps:["Doorway chest stretch: forearms on the frame, lean gently through: 30 seconds.","Cross-body shoulder stretch: 30 seconds per arm."],
    tips:["Keep breathing slowly."]},
  cool_cardio:{name:"Cool-down",q:"calf stretch hip flexor stretch",
    steps:["Easy pace on the crosstrainer for about 3 minutes.","Calf stretch against a wall: 30 seconds each leg.","Hip flexor stretch: 30 seconds each side."],
    tips:["Let your breathing settle before you stop moving."]},
  cool_rot:{name:"Cool-down stretches",q:"seated spinal twist childs pose",
    steps:["Seated spinal twist: 30 to 45 seconds each side.","Child's pose: 45 seconds."],
    tips:["Twist gently, using your breath to go a little further."]},
  cool_full:{name:"Full-body stretch",q:"full body stretch routine",
    steps:["Stretch whatever feels tight today.","Legs, hips, shoulders, and forearms are the usual suspects."],
    tips:["Relax into it."]}
};

/* ---------- Weekly plan ---------- */
var DAYS = [
  {id:"mon",short:"Mon",full:"Monday",focus:"Legs and core",
   equipment:"Bodyweight and light dumbbells",
   why:"Longsword guards and lunges live in the legs, and rotational core strength is what turns hip drive into an actual cut.",
   plan:[
    {ex:"warm_legs",time:300,after:15},
    {ex:"squat",sets:3,reps:"12 to 15 reps",rest:60},
    {ex:"bridge",sets:3,reps:"15 reps",rest:45},
    {ex:"lunge",sets:3,reps:"10 each leg",rest:60},
    {ex:"calf",sets:3,reps:"15 reps",rest:45},
    {ex:"plank",sets:3,time:30,rest:45},
    {ex:"side_plank",sets:2,time:20,sides:true,rest:30},
    {ex:"dead_bug",sets:2,reps:"10 each side",rest:30},
    {ex:"cool_legs",time:180}
   ]},
  {id:"tue",short:"Tue",full:"Tuesday",focus:"Rowing and grip",
   equipment:"Rower and light dumbbells",
   why:"Grip is usually the first thing to fail on a longsword. This trains hands and forearms directly, alongside the aerobic base that lets you last.",
   plan:[
    {ex:"warm_row",time:300,after:15},
    {ex:"row_steady",time:900},
    {ex:"farmer",sets:3,time:30,rest:60},
    {ex:"wrist_curl",sets:3,reps:"15 each direction",rest:45},
    {ex:"dead_hang",sets:3,reps:"Hold as long as you can",rest:60,optional:true},
    {ex:"cool_grip",time:120}
   ]},
  {id:"wed",short:"Wed",full:"Wednesday",focus:"Upper body and grip",
   equipment:"Bodyweight and light dumbbells",
   why:"This is where holding a sword up in guard stops being exhausting. Shoulders and upper back carry that load, not the arms alone.",
   plan:[
    {ex:"warm_upper",time:300,after:15},
    {ex:"pushup",sets:3,reps:"8 to 12 reps",rest:60},
    {ex:"db_row",sets:3,reps:"12 each side",rest:60},
    {ex:"press",sets:3,reps:"10 reps",rest:60},
    {ex:"rear_delt",sets:3,reps:"12 reps",rest:45},
    {ex:"rev_wrist",sets:2,reps:"15 reps",rest:45},
    {ex:"cool_upper",time:120}
   ]},
  {id:"thu",short:"Thu",full:"Thursday",focus:"Intervals",
   equipment:"Crosstrainer",
   why:"Armoured exchanges are short, brutal bursts. This builds the engine that lets you recover quickly between them.",
   plan:[
    {ex:"warm_cross",time:300,after:10},
    {ex:"intervals",sets:8,time:30,rest:90,restLabel:"Easy pace",restCue:"Keep moving at an easy pace.",after:10},
    {ex:"cool_cardio",time:300}
   ]},
  {id:"fri",short:"Fri",full:"Friday",focus:"Full body and rotation",
   equipment:"Bodyweight and light dumbbells",
   why:"Cuts come from hip and torso rotation, not the arms. This session builds a cut rather than just a swing.",
   plan:[
    {ex:"warm_rotation",time:300,after:15},
    {ex:"squat_press",sets:3,reps:"10 reps",rest:60},
    {ex:"plank_row",sets:3,reps:"8 each side",rest:60},
    {ex:"woodchop",sets:2,reps:"12 each side",rest:45},
    {ex:"russian",sets:3,reps:"16 total",rest:45},
    {ex:"bird_dog",sets:2,reps:"10 each side",rest:30},
    {ex:"cool_rot",time:150}
   ]},
  {id:"sat",short:"Sat",full:"Saturday",focus:"Active recovery",
   equipment:"Rower or crosstrainer",
   why:"Easy movement speeds up recovery more than sitting still. This one is deliberately light.",
   plan:[
    {ex:"easy_cardio",time:1080,after:15},
    {ex:"mobility",sets:2,time:180,rest:20},
    {ex:"cool_full",time:300}
   ]},
  {id:"sun",short:"Sun",full:"Sunday",focus:"Rest",rest:true,
   why:"This is where the actual adaptation happens. The week only works if you let this day be nothing.",
   plan:[]}
];
